export type Marketplace = 'dns' | 'ozon' | 'wildberries' | 'sunlight' | 'other';

export type ExpenseCategory = 
  | 'продукты' 
  | 'еда_вне_дома' 
  | 'транспорт' 
  | 'авто' 
  | 'покупки' 
  | 'развлечения' 
  | 'здоровье' 
  | 'подписки' 
  | 'подарки' 
  | 'дом' 
  | 'прочее';

export interface ExpenseItem {
  id: string;
  category: string;
  categoryType: ExpenseCategory;
  title: string;
  amount: number;
  time?: string;
  notes?: string;
  isConfirmed?: boolean;
  bankSource?: string; // e.g. "Т-Банк •4821"
}

export interface DayRecord {
  date: string; // 'YYYY-MM-DD'
  dayNumber: number; // 5, 6, 7...
  dayOfWeekShort: string; // 'Пт', 'Сб', 'Вс', 'Пн'...
  dayOfWeekFull: string; // 'Пятница', 'Суббота'...
  expenses: ExpenseItem[];
  spent: number;
  normLimit: number; // e.g. 1155.51
  deviation: number; // normLimit - spent (positive = economy, negative = overspend)
  budgetRemainingOnDate: number;
  totalRemaining: number;
  isToday?: boolean;
  isPast?: boolean;
}

export interface PlannedItem {
  id: string;
  title: string;
  amount: number; // Planned budget for the period (e.g. 18000.00 for "Бенз")
  spentAmount?: number; // Spent amount so far for progress-tracked items (e.g. 12000.00)
  isProgressTracked?: boolean; // If true, renders mini-progress achievement scale (plan vs fact)
  category: 'обязательные' | 'покупки' | 'игры_хобби' | 'авто' | 'мероприятия' | 'прочее';
  isPaid: boolean;
  notes?: string;
  plannedAmountAlt?: number; // e.g. 18000 / 12000
  period?: 'current' | 'next' | 'previous' | 'future' | 'advance_period' | 'salary_period' | string; // Перенос на другой период
  type?: 'regular' | 'credit_card' | 'food' | 'food_basket' | 'food_discretionary'; // Тип плановой статьи
  foodItemId?: string; // Связь с продуктом или категорией корзины
  creditCardId?: string; // Связь с объектом CreditCard при долговой стратегии
  isAutoGenerated?: boolean; // Создано автоанализом ИИ
  autoRenew?: boolean; // Автоматическое продление на будущие периоды
  sourceMerchant?: string; // Мерчант или контрагент (например, "МосОблЕИРЦ", "Ростелеком")
  typicalDay?: number; // Типичный день списания в месяце (1-31)
}

export interface SuggestedRegularExpense {
  id: string;
  merchant: string;
  title: string;
  amount: number; // Средняя или медианная сумма
  typicalDay: number; // Типичный день списания (1..31)
  periodicity: 'monthly' | 'weekly';
  confidence: number; // 0..1 (например 0.95 = 95%)
  isFixed: boolean; // true если коэффициент вариации < 30%
  predictedAmount?: number; // Прогноз суммы на следующий месяц (для нестабильных расходов вроде ЖКХ)
  category: 'обязательные' | 'покупки' | 'игры_хобби' | 'авто' | 'мероприятия' | 'прочее';
  occurrenceCount?: number; // Сколько раз встречался в выписке
  rawCategory?: string;
  notes?: string;
  historyAmounts?: number[];
  historyDates?: string[];
  autoRenew?: boolean;
}

export interface PaymentDateOptimizationAdvice {
  hasScatteredDates: boolean;
  suggestedDay: number;
  scatteredCount: number;
  earliestDay: number;
  latestDay: number;
  recommendationText: string;
  providersGuide: {
    name: string;
    category: string;
    howToChange: string;
    url?: string;
  }[];
  alternativeAdvice?: string;
}

export interface WishlistItem {
  id: string;
  title: string;
  url: string;
  marketplace: Marketplace;
  articleId?: string; // nmId on WB, product code on OZON/DNS
  price: number;
  isPurchased: boolean;
  priority: 'high' | 'medium' | 'low';
  category?: string;
  notes?: string;
  targetMonth?: string;
}

export interface CushionMonthPlan {
  year: number;
  monthName: string;
  targetAccumulated: number;
  monthlyDeposit: number;
  rateInfo: string;
  capitalization: number;
  expense: number;
  balance: number;
  deviation: number;
}

// ==========================================
// FOOD & GROCERIES MANAGEMENT TYPES
// ==========================================

export type FoodControlMode = 'simple' | 'basket' | 'hybrid';

export type FoodItemCategory = 
  | 'молочка' 
  | 'хлеб' 
  | 'мясо' 
  | 'рыба' 
  | 'крупы' 
  | 'овощи_фрукты' 
  | 'яйца' 
  | 'масло' 
  | 'напитки' 
  | 'сладости' 
  | 'заморозка' 
  | 'прочее';

export interface FoodItem {
  id: string;
  name: string;
  gtin?: string;
  price: number;
  quantityPerMonth: number;
  unit?: string; // e.g. "шт", "л", "кг", "уп", "бут"
  category?: FoodItemCategory;
  frequency?: 'daily' | 'every_2_days' | 'weekly' | 'biweekly' | 'monthly' | 'custom';
  lastUpdated: string;
  notes?: string;
  brand?: string;
  imageUrl?: string;
}

export interface FoodPriceHistoryEntry {
  month: string; // e.g. "Апрель 2026", "Май 2026", "Август 2026"
  period?: string; // e.g. "Август 2026"
  basketTotal: number;
  totalBasketCost: number;
  actualSpent?: number;
  changePercentage?: number;
  inflationRate?: number;
}

export interface FoodControlState {
  mode: FoodControlMode;
  monthlyLimit?: number; // для simple и hybrid
  discretionaryLimit?: number; // отдельный лимит на спонтанные продукты для hybrid
  basketItems?: FoodItem[];
  basketTotal?: number; // автоматически вычисляется
  lastUpdated?: string;
  priceHistory?: FoodPriceHistoryEntry[];
}

export interface MandatoryExpense {
  id: string;
  title: string;
  amount: number;
  category: string;
  isAutoCalculated?: boolean;
}

// ==========================================
// BANKING & SYNCHRONIZATION TYPES
// ==========================================

export type BankId = 'tbank' | 'sber' | 'alfa' | 'vtb' | 'raiffeisen' | 'gazprom' | 'other';

export interface BankAccount {
  id: string;
  bankId: BankId;
  bankName: string;
  accountType: 'checking' | 'savings'; // checking = дебетовая карта/основной, savings = накопительный счет/подушка
  accountName: string; // "Black Premium", "СберКарта", "Альфа-Счет"
  accountNumberMask: string; // "•4821"
  balance: number;
  interestRate?: number; // 13.5 (%)
  lastSyncedAt: string;
  isConnected: boolean;
  color: string;
}

export interface BankTransaction {
  id: string;
  bankAccountId: string;
  bankName: string;
  accountNumberMask: string;
  title: string;
  merchant: string;
  amount: number; // always positive for expense
  type: 'expense' | 'income' | 'transfer' | 'interest';
  categoryType: ExpenseCategory;
  categoryName: string;
  date: string; // 'YYYY-MM-DD'
  time: string; // 'HH:mm'
  status: 'pending' | 'approved' | 'rejected';
  isIncomeConfirmed?: boolean;
  rawSnippet?: string;
}

export type IncomeSourceType = 'salary' | 'advance' | 'bank_card' | 'cash' | 'transfer' | 'freelance' | 'bonus' | 'gift' | 'debt_return' | 'sale' | 'other';

export interface IncomeItem {
  id: string;
  title: string;
  amount: number;
  date: string; // 'YYYY-MM-DD'
  time?: string; // 'HH:mm'
  sourceType: IncomeSourceType;
  sourceName?: string; // "Т-Банк •4821", "Наличные", "СБП Перевод"
  category: string; // "Зарплата", "Аванс", "Перевод", "Наличные", "Кэшбэк", "Подработка", "Премия", "Возврат долга", "Продажа", "Подарок", "Прочее"
  isIncludedInBudget: boolean; // Включено ли в текущий расчет 30-дневного бюджета
  isManual: boolean; // Добавлено вручную пользователем
  bankTransactionId?: string; // Если создано на основе банковской входящей транзакции
  notes?: string;
  createdAt: string;
}

export interface BudgetState {
  periodTitle: string; // "05.08.2026 — 04.09.2026"
  periodStartDate: string; // "2026-08-05"
  periodEndDate: string; // "2026-09-04"
  todayDate: string; // "2026-08-28"
  
  // Advance and salary timeline
  salaryDateDay: number; // 5 (5th of month)
  advanceDateDay: number; // 20 (20th of month)
  advancePaymentDate: string; // "2026-08-20"
  estimatedAdvanceAmount: number; // 40 000.00 (estimated advance payment)
  isAdvanceReceived?: boolean; // Получен ли уже аванс в текущем периоде
  isSalaryReceived?: boolean; // Получена ли уже зарплата в текущем периоде
  salaryReceivedDate?: string; // Дата фактического поступления зарплаты
  actualSalaryAmount?: number; // Фактическая сумма зачисленной зарплаты
  
  // High-level budget
  total30DaysBudget: number; // 135 789.69
  previousMonthRemainder: number; // 11 803.76
  safetyCushionDeposit: number; // 8 265.00
  currentSalary: number; // 82 650.00
  
  // Balance sync state
  isBalanceSynced?: boolean;
  lastBalanceSyncDate?: string;
  
  // Planned items
  plannedItems: PlannedItem[];
  
  // Daily spending data
  days: DayRecord[];
  
  // Wishlist
  wishlist: WishlistItem[];
  
  // Safety cushion
  cushionAccumulated: number; // 8 269.53 (на счетах / вкладах)
  cushionCash: number; // Наличные сбережения
  cushionTargetAmount: number; // 163 294.11
  cushionTargetMonthsCount: number; // 3
  cushionMonthlyContribution: number; // Ежемесячное пополнение
  mandatoryExpenses: MandatoryExpense[];
  mandatoryExpensesMode?: 'manual' | 'auto';
  cushionSchedule: CushionMonthPlan[];
  isCushionDepositDoneThisMonth?: boolean; // Были ли совершен взнос в текущем месяце (август 2026)
  actualCushionDepositThisMonth?: number; // Сумма совершенного взноса (8 265.00)
  cushionNormMode?: 'percent' | 'fixed'; // Способ расчета нормы: процент от з/п или фиксированная сумма
  cushionNormPercent?: number; // Процент нормы (рекомендация: 10%)
  cushionNormFixedAmount?: number; // Фиксированная сумма нормы
  
  // Banking integration state
  bankAccounts: BankAccount[];
  pendingBankTransactions: BankTransaction[];
  lastBankSyncTimestamp?: string;
  
  // Income & additional inflows (card receipts, cash, freelance, gifts)
  incomes: IncomeItem[];
  
  // Credit cards management
  creditCards?: CreditCard[];
  
  // Regular expenses AI analysis state
  regularExpensesAnalyzed?: boolean;
  ignoredMerchants?: string[]; // Мерчанты, которые пользователь явно удалил/отклонил
  
  // Food & groceries management state
  foodControl?: FoodControlState;

  // Marketplace sync state (Wildberries & OZON)
  marketplaceSync?: MarketplaceSyncState;

  // User Profile & Preferences
  userName?: string;
  currency?: string; // 'RUB' | 'USD' | 'EUR'
  includeAdvanceInBudget?: boolean;

  // View mode
  isMobileFrame: boolean;
}

// ==========================================
// MARKETPLACE SYNC TYPES (WB & OZON)
// ==========================================

export interface MarketplaceOrder {
  id: string;
  marketplace: 'wildberries' | 'ozon';
  title: string;
  price: number;
  status: 'ordered' | 'delivered' | 'cancelled';
  orderDate: string;
  deliveryDate?: string;
  imageUrl?: string;
}

export interface MarketplaceSyncState {
  isWildberriesConnected: boolean;
  isOzonConnected: boolean;
  lastSyncedAt?: string;
  orders: MarketplaceOrder[];
}

// ==========================================
// CREDIT CARDS TYPES
// ==========================================

export type CreditCardStrategy = 'debt' | 'optimizer';

export interface CreditCard {
  id: string;
  bankName: string;
  cardMask: string; // e.g. "4589" or "•4589"
  creditLimit: number; // Кредитный лимит карты
  currentDebt: number; // Текущий остаток задолженности
  initialDebt?: number; // Начальный долг при регистрации
  gracePeriodEndDate: string; // 'YYYY-MM-DD' - Дата окончания беспроцентного периода
  strategy: CreditCardStrategy; // 'debt' (долговая с ежемесячным платежом) или 'optimizer' (грейс-оптимизатор)
  monthlyPayment?: number; // Сумма регулярного платежа для долговой стратегии (вычитается из бюджета)
  minPayment?: number; // Минимальный обязательный платеж (опционально)
  lastUpdated: string; // ISO date
  notes?: string;
  isPaidOff?: boolean; // Погашена ли карта полностью
}

// ==========================================
// FINANCIAL PROFILE TYPES
// ==========================================

export type IncomePattern = 'monthly' | 'biweekly' | 'weekly' | 'irregular';
export type WorkSchedule = '5_2' | '2_2' | 'shift' | 'flexible' | 'self_employed' | 'unemployed';
export type IncomeType = 'fixed' | 'fixed_with_variable' | 'variable' | 'irregular';

export interface FinancialProfile {
  id: string;
  // Основной профиль, предложенный ИИ
  profileType: 'stable' | 'salary_advance' | 'variable' | 'irregular' | 'freelance';
  // Параметры дохода
  mainSalaryDate: number; // день месяца (1-31), когда приходит основная зарплата
  advanceDate?: number; // день месяца для аванса (если есть)
  bonusDateDay?: number; // день месяца для выплаты премии (для профиля Оклад + Бонусы/KPI)
  regularPaymentsDay?: number; // день списания регулярных платежей (для Свой профиль/Самозанятый)
  hasVariablePart: boolean;
  fixedPartAmount: number; // сумма постоянной части (определяется ИИ)
  variablePartAverage?: number; // средняя переменная часть (если есть)
  // Режим учёта аванса: 'include_in_budget' или 'separate'
  advanceTreatment: 'include' | 'separate';
  // Дополнительные характеристики
  incomePattern: IncomePattern;
  workSchedule?: WorkSchedule;
  incomeType: IncomeType;
  // Настройки периода: начало периода – день основной зарплаты
  periodStartDay: number; // всегда равен mainSalaryDate
  // Флаг, что профиль создан вручную или автоматически
  isAutoDetected: boolean;
  // Дата создания
  createdAt: string;
  // Идентификатор пользователя (для Firebase)
  userId?: string;
}

// Расширяем BudgetState, чтобы включить профиль
export interface BudgetState {
  // ... все существующие поля ...
  financialProfile?: FinancialProfile; // добавляем это поле
  // также можно добавить флаг, что онбординг пройден
  isOnboardingCompleted?: boolean;
}

export type ActiveTab = 'today' | 'budget' | 'planning' | 'wishlist' | 'cushion' | 'analytics' | 'confirm-expenses';
